spring.application.name=multi-bambu-api

#Database configuration
spring.datasource.url=jdbc:postgresql://192.168.2.18:15432/bambu_db
spring.datasource.username=bambu_user
spring.datasource.password=jRcDhncYf970q56nxO91lS03wf
# Optional: can be omitted because Spring Boot can infer it from the JDBC URL.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Field-level encryption key (AES-256): Base64-encoded 32-byte key.
# Generate with: openssl rand -base64 32
encryption.key=RlxB8bEPPy844YVCCwQM8Js4/86kMxkBgafFsRai13E=